FROM python:3.11-slim

ENV DUCKDB_PATH=/data_warehouse/job_ads.duckdb

WORKDIR /app/dashboard

COPY dashboard/ /app/dashboard/

RUN pip install streamlit duckdb pandas plotly 

RUN pip install -e .

CMD ["streamlit", "run", "run_dashboard/Startsida.py", "--server.port=8501", "--server.address=0.0.0.0"]