version: "3.9"




services:
  bulk_pipeline:
    platform: linux/amd64 
    build:
      context: .
      dockerfile: dockerfile.bulk
    ports:
      - "3000:3000"
    image: cr4yoakl.azurecr.io/bulk_pipeline:latest


  pipeline:
    platform: linux/amd64 # mac m chip specific
    build:
      context: .
      dockerfile: dockerfile.dwh
    ports:
      - "3000:3000"
    image: cr4yoakl.azurecr.io/pipeline:latest

  dashboard:
    platform: linux/amd64 # mac m chip specific
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports:
      - "8501:8501"
    image: cr4yoakl.azurecr.io/dashboard:latest